networks:
  default:
    driver: bridge
    name: roboshop
services:
  mongodb:
    image: venky7031/mongodb:v1
    container_name: mongodb
  catalogue:
    image: venky7031/catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: venky7031/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: venky7031/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: venky7031/mysql:v1
    container_name: mysql
  shipping:
    image: venky7031/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart